[package]
name = "minql-uri"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { version = "7" }
owning_ref = { version = "0.4" }
tracing = { version = "0.1" }

[dev-dependencies]
tracing-test = { version = "0.2" }