[package]
name = "minql-vfs"
version = "0.1.0"
edition = "2021"

[dependencies]
fs2 = { version = "0.4.3" }
minql-uri = { path = "../minql-uri" }
tracing = { version = "0.1.40" }

[dev-dependencies]
tracing-test = { version = "0.2" }